name: VWA Multi-Arch Build Test
on:
  push:
    branches:
      - master
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  IMG: volumes-web-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build multi-arch Image
      run: |
        cd components/crud-web-apps/volumes
        ARCH=linux/ppc64le make docker-build-multi-arch
